### ISSUE TITLE
Can't upload

### ISSUE THREAD

**Issue by skylogic004** [mistic100/Piwigo-URL-Uploader#1]
I'm having issues getting things to upload. I always get "an error occurred" popups.

I'm trying to debug the problem myself, but I'm not too familiar with PHP / JS / Piwigo, so my question is, how does the javascript file (photos_add.tpl) know where to access 'ws.php', given that the true filename is 'ws_functions.inc.php'?

Reason: I suspect the PHP function isn't getting called, so I want to double check that the right file is getting called from this code:
  function performImport(file_url, category, name, level, url_in_comment, $target) {
    queuedManager.add({
      type: 'GET',
      dataType: 'json',
      url: 'ws.php',
      ....

Thanks,
Matt

**Comment by elespike** [comment]
Fixed!
