### ISSUE TITLE
No ability to add tags in API

### ISSUE THREAD

**Issue by belldandu** [mistic100/Piwigo-URL-Uploader#2]
I normally add tags along with categories. Any chance you can add tags as something optional in the api for addRemote?

**Comment by mistic100** [comment]
I don't really work on Piwigo anymore. As there is the core method "pwg.images.setInfo" which can be used to add tags, this is low priority.

**Comment by belldandu** [comment]
Yes ik but calling 2 seperate api's only for the second call to add a tag seems silly. It would be better if you could add the tag when you call the first api.
