### ISSUE TITLE
Ownership transfer

### ISSUE THREAD

**Issue by elespike** [mistic100/Piwigo-URL-Uploader#4]
Hello!

I'd like to maintain this going forward. =)

**Comment by mistic100** [comment]
Yeah sure, what is your username on http://piwigo.org/ext

**Comment by elespike** [comment]
Same as here, elespike:
http://piwigo.org/forum/profile.php?id=23922

**Comment by mistic100** [comment]
Added as contributor on both platforms, welcome :-)

**Comment by elespike** [comment]
Thank you! :D
